class Product < ApplicationRecord
    belongs_to :user
    has_one_attached :image

    CATEGORY_LIST = [
        ['---String Family---', {disabled: 'disabled'}],
        'Banjo',
        'Cello',
        'Cittern',
        'Guitar',
        'Harp',
        'Lute',
        'Upright Bass',
        'Viola',
        'Violin',
        ['---Woodwind Family---', {disabled: 'disabled'}],
        'Clarinet',
        'Flute',
        'Oboe',
        'Pipe',
        'Recorder',
        'Reeds',
        'Saxophone',
        ['---Percussion Family---', {disabled: 'disabled'}],
        'Acoustic Drum Set',
        'Bells',
        'Cymbals',
        'Castanets',
        'Congas',
        'Electric Drum Set',
        'Frame Drums',
        'Hand Drums',
        'Maracas',
        'Xylophone',
        ['---Brass Family---', {disabled: 'disabled'}],
        'Bugle',
        'Cornet',
        'Euphonium',
        'Flugelhorn',
        'Helicon',
        'Horn',
        'Mellophone',
        'Trombone',
        'Trumpet',
        'Tuba',
        ['---Keyboard Family---', {disabled: 'disabled'}],
        'Accordions & Concertinas',
        'Harpsichord',
        'Keyboard',
        'Piano',
        'Sound Synthesizers'
      ]
end
